# Generated by Django 4.2.25 on 2025-11-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('voiture', models.CharField(blank=True, max_length=100, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('permis', models.CharField(max_length=50)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chauffeur',
            },
        ),
    ]
